name: "Deploy to GitHub Pages"

on:
    push:
        branches:
            - main
jobs:
    deploy:
        permissions:
          contents: write
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: pnpm/action-setup@v4
            with:
              version: 7.29.1
              run_install: false
          - name: Use Node.js 18
            uses: actions/setup-node@v4
            with:
              node-version: 18
              cache: "pnpm"
          - name: Install dependencies
            run: pnpm install --frozen-lockfile --strict-peer-dependencies
          - name: Build
            run: pnpm run build
          - name: Deploy
            uses: peaceiris/actions-gh-pages@v4
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./dist
    